### ISSUE TITLE
git-stats --authors truncates top not bottom

### ISSUE THREAD

**Issue by erwald** [IonicaBizau/git-stats#126]
When using `git-stats --authors` in a repository with a lot of contributing authors (>35), the topmost authors are cut off. I think it'd make more sense to show the "leading" contributors and cut off at the bottom, maybe even with "..." or similar, to show the list has been truncated.

**Comment by xeoshow** [comment]
@IonicaBizau Hello, has the bug been resolved now ? Really need it ... Thanks!

**Comment by jamalsoueidan** [comment]
No it's still an issue.

**Comment by kingthorin** [comment]
I just hit this using the pie chart and using a --since of 2010 (our projects has 100s of contributors). It would be great if, either:
1) There was a switch for this to be top 35 instead of bottom 35 (or that top was default).
2) There was an option to center the graph beside a full list of contributors.

**Comment by kingthorin** [comment]
Thanks for fixing this @DenverCoder1, thanks for merging the fix @IonicaBizau 😀
