### ISSUE TITLE
Graph current repository

### ISSUE THREAD

**Issue by fedosov** [IonicaBizau/git-stats#13]
How does one can graph current (working directory) repository commitments? Can `git-stats` take this information from `git log`?

**Comment by IonicaBizau** [comment]
Currently this is no possible (see #8).

But I will think how I can improve it. In the mean time you can do:

```sh
$ mv ~/.git-stats ~/.git-stats.old
$ cd path/to/current-repo
$ git-stats-importer
$ git-stats
$ mv ~/.git-stats.old ~/.git-stats
```

**Comment by wimleers** [comment]
Without support for `git log`, it's impossible to use this for many kinds of projects. E.g. [in Drupal core](http://cgit.drupalcode.org/drupal/log/), there are only a handful of committers. These few committers commit dozens of patches per day, and they attribute people by their Drupal.org nickname.

So, to make `git-stats` work on Drupal core (currently the `8.0.x` branch), it'd be necessary to not only support `git log` and looking at the author, but also to ignore the author and parse the nicknames (format: `[…] by user1, user2, …, userN: […]`) from the commit message.

(We don't use a pull request/merge-based workflow in Drupal. We use patches.)

**Comment by IonicaBizau** [comment]
@williamboman Glad to see a Drupal developer here. :smile: I will keep that in mind. However, I can't make any promises if we will implement that, but it's definitely an issue.

But my question is why do not users commit there using their git data (user & email)?

**Comment by wimleers** [comment]
Of course, I completely understand you can't make promises :)

`git`'s authoring attribution is quite (ridiculously IMO) limited. In Drupal, usually a whole bunch of people collaborate on a patch. There's often no sensible "primary author" that can be selected. The first listed user is usually the one who worked the most on the patch. So that'd be a good candidate. But how do you that reflect that sensibly in the commit then? If the primary author is used in the `--author` flag, but the other authors are in the commit message, that's also confusing, because now the data lives in two places. That, and many more considerations (including the entire commit history using this format — Drupal predates `git` by many years), make doing that a far-from-great choice for Drupal.

**Comment by wimleers** [comment]
Here are a few examples:

- one author: ```* 2847b59 - Issue #2453059 by Wim Leers: Set default render cache contexts: 'theme' + 'languages:' . LanguageInterface::TYPE_INTERFACE (16 hours ago) <Alex Pott>```
- multiple authors: ```* ea08182 - Issue #2462151 by hussainweb, benjy: Remove unused Utility\String use statements (18 hours ago) <Alex Pott>```
- very many authors: ```* 841e4a9 - Issue #1847596 by amateescu, amitaibu, YesCT, Berdir, David_Rothstein, xjm, rteijeiro, ParisLiakos, webchick, Wim Leers, yched, jhodgdon, Bojhan: Remove Taxonomy term reference field in favor of Entity reference (3 days ago) <webchick>```

**Comment by IonicaBizau** [comment]
That's a neat idea! :+1: 

I would like to extend the library API and the command line script with these options. See #38 for more details.

**Comment by IonicaBizau** [comment]
In #51 I'm adding an author visualization in the current repository. :four_leaf_clover: 

@wimleers Do you have any ideas how could we integrate a Drupal commit message parser into this project? It would be easier to write another tool which will be Drupal specific and will generate dummy repositories with the correct authors.

**Comment by IonicaBizau** [comment]
In #55 I implemented this feature. The more active the project is, the greener squares are. :green_apple:
