### ISSUE TITLE
With fewer columns, the left side of the calendar should be hidden, not the right

### ISSUE THREAD

**Issue by philadams** [IonicaBizau/git-stats#28]
When you've got less columns in your terminal, you really want to see the most recent activity in detail rather than the earliest (1 year old).

So, in the attached screenshot, given the activity in the second calendar, the first (printed when the window was much narrower) should really show the most recent _n_ months with left-side ellipses, rather than the older _n_ months and right-side ellipses.

![screen shot 2015-02-18 at 10 53 47 am](https://cloud.githubusercontent.com/assets/8108/6250581/c4f19d16-b75c-11e4-95b5-df1a0c60d167.png)

**Comment by furgerf** [comment]
There seems to be another bug related to terminal width, this is how the calendar looks on my half-width terminals:

![2015-05-04-084346_1600x900_scrot](https://cloud.githubusercontent.com/assets/5868970/7450224/485a1c06-f23a-11e4-8a46-c5e074e7499c.png)

I assume my bug is caused by git-stats-colors which appears to add another column, since --no-ansi displays correctly.

I'd say that there are 2 possible solutions philadams' issue: either check the terminal column width before creating the calendar and potentially remove (old!) commit information, or check the output generated by node-cli-box to see whether it contains dots (i.e. whether the output is too long) and re-run the function with one column less until there aren't too many columns anymore.

Solution 1 clearly is more tidy but that would lead to having duplicate code in node-cli-box and git-stats (doing all the terminal width checks twice). Handling terminal width in git-stats would allow solving my issue as well though.

**Comment by IonicaBizau** [comment]
The box is generated via [`cli-box`](https://github.com/IonicaBizau/node-cli-box). It is smart enough to trim the content on the right side. Maybe we should consider adding a new option to trim the content on the left side.

Anyways, what @furgerf observe is because of [these two lines](https://github.com/IonicaBizau/node-git-stats-colors/blob/8daf0dc7055419e4944f1693eb956641fa4cb567/lib/index.js#L53-L54).

If you like to fix these issues, please let me know how we can organize. :smile:

**Comment by furgerf** [comment]
Trimming on the left side would remove the weekday names... As I see it there's no way around modifying the data passed to the calendar that contains the commit information, either when it is determined that the width wouldn't be sufficient before the calendar is created (my proposed solution 1) or after it the calendar was created and the box trimmed its contents (solution 2).

**Comment by IonicaBizau** [comment]
> Trimming on the left side would remove the weekday names... 

Very good point. :+1: Then, we have to handle this in the executable script from git-stats (or maybe in the `git-stats-colors` module).

**Comment by furgerf** [comment]
Why in `git-stats-colors`? The problem isn't caused by the coloring but also exists when using --no-ansi

**Comment by IonicaBizau** [comment]
@furgerf You're right. Most probably the solution will be in the library code since there is created the box.

**Comment by IonicaBizau** [comment]
Since I separated the GitHub like calendar for cli in another package ([`cli-gh-cal`](https://github.com/IonicaBizau/cli-gh-cal)) we can solve these issues there. Anyone who would like to fix this? /cc @fnogatz

**Comment by IonicaBizau** [comment]
This should be fixed now via https://github.com/IonicaBizau/cli-gh-cal/pull/12.

`npm i -g git-stats@latest` should be enough. :tada:
