### ISSUE TITLE
Reason for remote url?

### ISSUE THREAD

**Issue by clementop** [IonicaBizau/git-stats#29]
I'm curious about your decision for making the remote url of the repository a requirement for a git stats record.

When I read "...but locally, with all your git commits.", I imagined that the graph would be aggregating data across all of my commits (at least the repositories I have imported). Many of my repositories are just kept locally -- they are not connected to any remotes.

Is git-stats intended to only aggregate _public_ contributions?

**Comment by IonicaBizau** [comment]
Because in the future I may add more stats, maybe listing the repositories and how active was their development in the time.

So, having a remote url is probably the best technique to namespace the repositories.

I was also thinking at something like:

```js
{
    "config": { /* defaults */}
  , "commits": { "hash": "date" }
  , "urls": { "remote-url": ["hash1", "hash2", ... ] }
}
```

Maybe we will change it this way. See this related discussion too: https://github.com/IonicaBizau/git-stats-importer/issues/1

**Comment by IonicaBizau** [comment]
And sure, if you have any ideas post comments here.
