### ISSUE TITLE
`--since` option not applied when used together with `--authors` option

### ISSUE THREAD

**Issue by renzhn** [IonicaBizau/git-stats#79]
It should show authors' contributions pie chart since that day to make sense, I think.

**Comment by renzhn** [comment]
https://acassis.wordpress.com/2009/07/16/getting-git-revision-by-specific-date/

**Comment by IonicaBizau** [comment]
@renzhn Thanks amazing point! :sparkles: 

Currently this is not supported, but it would be neat to be supported.
This should be implemented [here](https://github.com/IonicaBizau/git-stats/blob/0407c10643114ef2030edb2fa26fc8d912011111/lib/index.js#L528), like you said using `since` and `until`. :sparkler:

**Comment by renzhn** [comment]
@IonicaBizau Also I noticed `git shortlog` counts each author's commit, not lines of code. I think this should be clarified as users don't know how contributions are counted.

**Comment by IonicaBizau** [comment]
@renzhn True. I guess this is how GitHub sorts the repo contributors as well (the more commits you have, the higher in top you are). Obviously, we should improve the docs in this direction. :memo
